version: '3.9'

services:
  rip:
    build: images/python_rip
    container_name:  rip
    command:
      - '-f'
      - "2017-01-01"
    volumes:
    - ./data:/data
    - ./rip:/rip

  rstudio:
    build: images/rstudio
    container_name: rstudio
    ports:
      - '8787:8787'
    volumes:
      - "./notebooks/:/home/rstudio/notebooks:rw"
      - "./data:/home/rstudio/data:rw"

    environment:
      - DISABLE_AUTH=true
      - ROOT=TRUE
volumes:
  data:
    external: true
